version: "3.7"

services:
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - ../data/db:/var/lib/postgresql/data
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./sql/init_card.sql:/docker-entrypoint-initdb.d/init_card.sql
    environment:
      - POSTGRES_DB=sql
      - POSTGRES_USER=sql
      - POSTGRES_PASSWORD=sql
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0.5-alpine
    command: redis-server
    environment:
      - REDIS_PORT=6379
    ports:
      - "6379:6379"

