version: "3.7"

services:
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0.5-alpine
    command: redis-server
    environment:
      - REDIS_PORT=6379
    ports:
      - "6379:6379"

