# Generated by Django 4.2.1 on 2023-05-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=16)),
                ("card_type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="images/")),
                ("cost", models.IntegerField()),
                ("score", models.IntegerField()),
                ("condition", models.CharField(max_length=100)),
                ("command", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("is_use", models.BooleanField(default=False)),
            ],
        ),
    ]
