# Generated by Django 4.2.1 on 2023-06-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('card_type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('command', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CardEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('effect', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=800)),
            ],
        ),
    ]
