# Generated by Django 4.2.1 on 2023-06-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='condition',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cost',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
