# Generated by Django 4.2.1 on 2023-06-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(default='이미지 참조', max_length=100),
        ),
    ]
