# Generated by Django 4.2.1 on 2023-06-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('effect', models.CharField(max_length=10)),
                ('command', models.CharField(max_length=200)),
            ],
        ),
    ]
