# Generated by Django 4.2.1 on 2023-06-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_condition_card_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardeffect',
            name='command',
            field=models.CharField(max_length=400),
        ),
    ]
