# Generated by Django 4.2.1 on 2023-06-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='condition',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cost',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
